export async function POST(req: Request) {
  const { repoUrl, language } = await req.json();

  // TODO: Integrate with LLM for real generation
  // For now, return a template
  
  const readme = `# ${repoUrl.split('/').pop()}

🚀 Auto-generated documentation

## Overview

This project is built with ${language || 'JavaScript/TypeScript'}. 
It was analyzed and documented automatically by RepoDocs.ai.

## Installation

\`\`\`bash
# Clone the repository
git clone ${repoUrl}
cd ${repoUrl.split('/').pop()}

# Install dependencies
npm install
\`\`\`

## Usage

\`\`\`bash
# Run the project
npm run dev
\`\`\`

## API Documentation

*Generated automatically from source code*

## Contributing

1. Fork the repository
2. Create a feature branch
3. Submit a pull request

---

*Generated by [RepoDocs.ai](https://repodocs.ai) — Documentation that stays current* ✨
`;

  return Response.json({ success: true, readme });
}
