import { Idea } from './types';

export const sampleIdeas: Idea[] = [
  {
    id: '1',
    title: 'AI Content Repurposing SaaS',
    description: 'Automatically transform long-form videos into short clips, blog posts, and social media content.',
    problem: 'Content creators spend 80% of their time on distribution vs creation',
    solution: 'AI-powered repurposing that extracts key moments and reformats for each platform',
    targetMarket: 'YouTubers, podcasters, and content teams',
    revenueModel: 'Subscription ($29-99/month based on volume)',
    scores: {
      marketSize: 9,
      competition: 7,
      technicalFeasibility: 8,
      personalFit: 9,
    },
    status: 'Building',
    notes: 'Similar to ContentClaw but more automated. Could integrate with YouTube API.',
    createdAt: '2026-01-15',
    updatedAt: '2026-01-30',
  },
  {
    id: '2',
    title: 'MCP Gateway Security',
    description: 'Security layer for Model Context Protocol connections with auth and rate limiting.',
    problem: 'MCP servers have no built-in authentication or security controls',
    solution: 'Gateway that sits between clients and MCP servers with API keys, rate limits, and logging',
    targetMarket: 'AI infrastructure companies and enterprises',
    revenueModel: 'Usage-based ($0.001 per request)',
    scores: {
      marketSize: 7,
      competition: 3,
      technicalFeasibility: 9,
      personalFit: 8,
    },
    status: 'Researching',
    notes: 'Emerging market as MCP adoption grows. First-mover advantage possible.',
    createdAt: '2026-01-20',
    updatedAt: '2026-01-28',
  },
  {
    id: '3',
    title: 'Voice AI for Indian Languages',
    description: 'Voice assistant focused on Indic languages for rural accessibility.',
    problem: 'Most voice AI only supports English and major languages; 1B+ Indians underserved',
    solution: 'Fine-tuned models for Hindi, Tamil, Telugu, Bengali with local dialect support',
    targetMarket: 'Rural India, fintech, edtech',
    revenueModel: 'B2B API + consumer app freemium',
    scores: {
      marketSize: 10,
      competition: 4,
      technicalFeasibility: 6,
      personalFit: 7,
    },
    status: 'Validating',
    notes: 'Huge TAM. Need to validate technical feasibility with OpenAI Whisper alternatives.',
    createdAt: '2026-01-25',
    updatedAt: '2026-01-31',
  },
  {
    id: '4',
    title: 'AI-Powered Code Review',
    description: 'Automated security and quality checks for pull requests.',
    problem: 'Security vulnerabilities often make it to production due to manual review gaps',
    solution: 'AI agent that reviews every PR for security, performance, and best practices',
    targetMarket: 'DevOps teams, security-conscious startups',
    revenueModel: '$10-50 per developer/month',
    scores: {
      marketSize: 8,
      competition: 8,
      technicalFeasibility: 7,
      personalFit: 6,
    },
    status: 'Archived',
    notes: 'Too crowded with GitHub Copilot, Snyk, etc. Pivot to something more specific?',
    createdAt: '2026-01-10',
    updatedAt: '2026-01-22',
  },
];
