#!/bin/bash
# performance-report.sh - Generate performance tracking report

echo "📊 Social Media Performance Report"
echo "=================================="
echo "Date: $(date '+%Y-%m-%d')"
echo ""

echo "ℹ️  Note: This is a template. To track actual performance:"
echo "   1. Export engagement data from LinkedIn, X, Reddit"
echo "   2. Store in performance-tracking.md"
echo "   3. Run this report weekly"
echo ""

echo "📈 METRICS TO TRACK"
echo "------------------"
echo ""
echo "LinkedIn:"
echo "  - Impressions"
echo "  - Engagement rate"
echo "  - Profile views"
echo "  - Connection requests"
echo ""
echo "X/Twitter:"
echo "  - Impressions"
echo "  - Engagements"
echo "  - Profile visits"
echo "  - New followers"
echo ""
echo "Reddit:"
echo "  - Upvotes"
echo "  - Comments"
echo "  - Awards"
echo "  - Profile views"
echo ""

echo "🏆 TOP PERFORMING CONTENT"
echo "------------------------"
echo ""
echo "Check: /home/ubuntu/clawd/agents/social-media-manager/best-performing-posts.md"
echo ""
