#!/bin/bash
# show-schedule.sh - Show upcoming content schedule

echo "📅 Content Posting Schedule"
echo "=========================="
echo "Timezone: IST (India Standard Time)"
echo ""

echo "📱 DAILY ROUTINE"
echo "---------------"
echo ""
echo "9:00 AM  - ContentClaw generates posts from trending videos"
echo "9:15 AM  - Steve reviews and sends you the curated package"
echo "11:00 AM - 🟦 LINKEDIN (Optimal time)"
echo "4:00 PM  - 🐦 X/TWITTER (Optimal time)"
echo "7:00 PM  - 🔴 REDDIT (Optimal time)"
echo "9:00 PM  - ContentClaw evening run (for next day)"
echo ""

echo "📊 BEST POSTING TIMES (Research-Based)"
echo "--------------------------------------"
echo ""
echo "LINKEDIN:"
echo "  - Best: Tuesday-Thursday 10 AM - 12 PM"
echo "  - Good: Monday, Friday 10 AM"
echo "  - Avoid: Weekends"
echo ""
echo "X/TWITTER:"
echo "  - Best: Tuesday-Thursday 2 PM - 4 PM"
echo "  - Good: Monday 8 AM, Friday 3 PM"
echo "  - Avoid: Late nights"
echo ""
echo "REDDIT:"
echo "  - Best: Varies by subreddit"
echo "  - r/startups: Weekday evenings 6-9 PM"
echo "  - r/SaaS: Tuesday-Thursday afternoons"
echo "  - r/Entrepreneur: Weekend mornings"
echo ""

echo "🎯 CONTENT STRATEGY"
echo "------------------"
echo ""
echo "MONDAY:    Week planning, motivation"
echo "TUESDAY:   Educational content (best engagement)"
echo "WEDNESDAY: Thought leadership"
echo "THURSDAY:  Case studies, insights"
echo "FRIDAY:    Achievements, week recap"
echo "WEEKEND:   Light content, personal stories"
echo ""
